Traduzir em pt_BR domínios eea e plone relacionados ao eea.facetednavigation e brasil.gov.facetada.
plonegovbr/brasil.gov.facetada pull request #11
Opened 2018-05-10 12:36 UTC by idgserpro

foram traduzidos para pt_BR as seguintes expressoẽs abaixo: 

Default sorting index (e.g. 'effective' or 'effective(reverse)')

Filter from vocabulary

Vocabulary to use to filter sorting criteria. Leave empty for default sorting criteria

Hidden

Operator visible

Faceted items summary view

Faceted items preview

Boolean, Text field with suggestions

Let the end-user choose to search with AND or OR between elements

Wildcard search

Default value

Hide 'All' option

If this checkbox is checked, hides the All option

If this checkbox is checked, the system will automatically do a wildcard search by appending a '*' to the search term so searching for 'budget' will also return elements containing 'budgetary'

Autocomplete

Can select several elements

Indíces de catalogo :review_state

Select the source of the autocomplete suggestions

2018-05-10 12:54 UTC, hvelarde approved these changes
LGTM

2018-05-10 12:55 UTC, hvelarde commented
conseguem, por gentileza, arrumar a configuração de integração contínua num outro pull request?

2018-05-14 13:48 UTC, idgserpro commented
Sim, fizemos isto ,favor validar o pull request

2018-05-14 13:49 UTC, idgserpro commented
da branch de correção da integração contínua

2018-05-14 14:46 UTC, hvelarde requested changes
falta uma entrada no changelog.

2018-05-17 12:56 UTC, hvelarde requested changes
arrumei o rebase para vocês; continua faltando uma entrada no changelog.

2018-05-17 15:51 UTC, idgserpro commented
Correções feitas conforme solicitado

2018-05-17 18:21 UTC, hvelarde requested changes

2018-05-17 18:21 UTC, hvelarde commented on CHANGES.rst
> +1.0b3 (unreleased)
acho que temos algo errado aqui; as mudanças do @claytonc ainda não têm release.

2018-05-17 21:33 UTC, hvelarde approved these changes

2018-05-17 21:33 UTC, merged